hpcdata<-read.table("household_power_consumption.txt",header=FALSE,na.strings="?",sep=";", colClasses = "character",skip=1)
dT<-strptime(hpcdata[,1],"%d/%m/%Y")
timeStart<-strptime("2007-02-01","%Y-%m-%d")
timeEnd<-strptime("2007-02-02","%Y-%m-%d")
mydata<-subset(hpcdata,dT==timeStart|dT==timeEnd)
xaxis<-as.POSIXct(paste(mydata[,1],mydata[,2]),format="%d/%m/%Y%H:%M:%S")
submeter1<-as.numeric(mydata[,7])
submeter2<-as.numeric(mydata[,8])
submeter3<-as.numeric(mydata[,9])
png(filename="plot3.png",width=480,height=480)
plot(xaxis,submeter1,type="l",xlab="",ylab="Energy sub metering")
lines(xaxis,submeter2,col="red")
lines(xaxis,submeter3,col="blue")
legend("topright",lwd=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()
