hpcdata<-read.table("household_power_consumption.txt",header=FALSE,na.strings="?",sep=";", colClasses = "character",skip=1)
dT<-strptime(hpcdata[,1],"%d/%m/%Y")
timeStart<-strptime("2007-02-01","%Y-%m-%d")
timeEnd<-strptime("2007-02-02","%Y-%m-%d")
mydata<-subset(hpcdata,dT==timeStart|dT==timeEnd)
gap<-as.numeric(mydata[,3])
xaxis<-as.POSIXct(paste(mydata[,1],mydata[,2]),format="%d/%m/%Y%H:%M:%S")
png(filename="plot2.png",width=480,height=480)
plot(xaxis,gap,type="l",xlab="",ylab="Global active power(kilowatts)")
dev.off()