hpcdata<-read.table("household_power_consumption.txt",header=FALSE,na.strings="?",sep=";", colClasses = "character",skip=1)
dT<-strptime(hpcdata[,1],"%d/%m/%Y")
timeStart<-strptime("2007-02-01","%Y-%m-%d")
timeEnd<-strptime("2007-02-02","%Y-%m-%d")
mydata<-subset(hpcdata,dT==timeStart|dT==timeEnd)
gap<-as.numeric(mydata[,3])
png(filename="plot1.png",width=480,height=480)
hist(gap,main="Global Active Power",xlab="Global Active Power(kilowatts)",col="red")
dev.off()